# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('body', models.TextField()),
                ('optional_image', models.ImageField(blank=True, upload_to='', verbose_name='Optional Image')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='OfficerListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trio_title', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('job_title', models.CharField(max_length=80)),
                ('job_details', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=14)),
                ('optional_phone', models.CharField(blank=True, max_length=14)),
                ('optional_fax', models.CharField(blank=True, max_length=14)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
