# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trio_nm_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
