# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trio_nm_main', '0002_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='slug',
            field=models.SlugField(default='eventtest', max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
