# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trio_nm_main', '0003_calendarevent_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_name', models.CharField(max_length=120)),
                ('application_deadline', models.DateTimeField()),
                ('application_link', models.CharField(max_length=240)),
                ('contact', models.CharField(max_length=240)),
            ],
        ),
    ]
