# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trio_nm_main', '0004_scholarshiplisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchieverProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=140)),
                ('posting_date', models.DateTimeField()),
                ('text_body', models.TextField(max_length=2048)),
                ('optional_image', models.ImageField(blank=True, upload_to=b'', verbose_name=b'Optional Image')),
            ],
        ),
    ]
