# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trio_nm_main', '0007_auto_20161012_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='slug',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='optional_link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
