# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trio_nm_main', '0008_auto_20161012_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achieverprofile',
            name='text_body',
            field=models.TextField(max_length=2648),
        ),
    ]
